version: '3'

services:
  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    hostname: elasticsearch
    container_name: els
    environment:
      - discovery.type=single-node # Run Elasticsearch as a single-node cluster
      - xpack.security.enabled=false # Disable X-Pack security features
    ports:
      - '9200:9200' # Expose the HTTP API port
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elasticnetwork

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.7.1
    ports: 
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elasticnetwork
    
 



  nginx:
    container_name: ADOPSE-nginx
    image: nginx:1.21.3
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ClientApp/build:/usr/share/nginx/html
    networks:
      - adopse_net
    depends_on:
      - backend
    profiles:
      - stage

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ADOPSE-backend
    networks:
      adopse_net:
    # environment:
    #   ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - ./bin/Release/net7.0/linux-x64/publish:/App
    depends_on:
      mysql:
        condition: service_healthy
    profiles:
      - stage

  mysql:
    image: mysql:latest
    container_name: mysqladopse
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    profiles:
      - stage
    networks:
      adopse_net:

  mysqldev:
      image: mysql:latest
      container_name: mysqlDev
      restart: unless-stopped
      ports: 
        - "3333:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: mysql
      profiles:
       - dev
      networks:
        adopse_dev:
          

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    profiles:
      - dev
    networks:
      adopse_dev:
 
networks:
  adopse_net:
  adopse_dev:
  elasticnetwork:
    driver: bridge

volumes:
  elasticsearch-data: