version: '3'

services:

  nginx:
    container_name: ADOPSE-nginx
    build: 
      context: ./ClientApp
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - adopse_net
    depends_on:
      - backend
    profiles:
      - stage

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ADOPSE-backend
    networks:
      adopse_net:
    environment:
      ASPNETCORE_ENVIRONMENT: deployment
    depends_on:
      mysql:
        condition: service_healthy
    profiles:
      - stage

  mysql:
    image: mysql:latest
    container_name: mysqladopse
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    profiles:
      - stage
    networks:
      adopse_net:

  mysqldev:
      image: mysql:latest
      container_name: mysqlDev
      restart: unless-stopped
      ports: 
        - "3333:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: mysql
      profiles:
       - dev
      networks:
        adopse_dev:
          

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    profiles:
      - dev
    networks:
      adopse_dev:
 

networks:
  adopse_net:
  adopse_dev:      
